name: Test Kontrol

on: 
  workflow_dispatch:
    inputs:
      FOUNDRY_PROFILE: 
        description: 'The Foundry profile to use'
        required: false
  pull_request:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  kontrol-test:
    strategy:
      fail-fast: true
    concurrency: kontrol-ci-demo-${{ github.ref_name }}

    name: Kontrol Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Kontrol
        uses: runtimeverification/install-kontrol@v1.0.1
        with:
          version: latest
        
      - name: Run Kontrol
        run: kontrol build
      