name: Test Foundry

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    concurrency: kontrol-ci-demo-${{ github.ref_name }}
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
